# Generated by Django 4.2.4 on 2025-01-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intel_app', '0002_agentvodabundleprice_superagentvodabundleprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bigtimetransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='isharebundletransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='mtntransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='vodafonetransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
